### ISSUE TITLE
How to Run this project

### ISSUE THREAD

**Issue by TharinduK97** [XBWer/AnswerBot#1]
I am very sorry to ask that because I am new to this subject

**Comment by maxxbw54** [comment]
Hi @TharinduK97 , thanks for your interest. I have not maintained this tool for a while so I am unsure if it can be set up smoothly now. However, please kindly check my latest work with more advanced techinques on this task here https://github.com/TechSumBot/TechSumBot. And let me know if you meet any set-up issues.

**Comment by TharinduK97** [comment]
Thank you for your response Brad !
